[tool.poetry]
name = "cronhash"
version = "0.1.0"
description = "hashes a url"
authors = ["Ri Le <rl2999@columbia.edu>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
